### ISSUE TITLE
update single view

### ISSUE THREAD

**Issue by FunnyDevs** [dmitry-zaitsev/BlueTape#7]
Is possibile to update single view instead of all???

**Comment by dmitry-zaitsev** [comment]
Normally you would not need to update one view. The whole purpose of the library is that you define the rules for the whole layout instead of tweaking individual views. Perhaps if you'll give me an example of what you're trying to solve I can give some advice.

**Comment by FunnyDevs** [comment]
It's only a performance problem. If i bind many views with many properties and i want to update a (example) text of TextView, update() call a lot of methods (for all views)

**Comment by dmitry-zaitsev** [comment]
Most views do not perform any heavy operations when you are updating them. Moreover, since an update of all views happens simultaneously it, in fact, might even increase performance since re-measuring, re-layout and re-drawing of views happen only once.

Do you have a particular example which suffers from poor performance?

**Comment by FunnyDevs** [comment]
I have used heavily your library yet, but i have used anvil that has similar approach of your and i notice, with a complex layout, updating view has some problem. 
However i want to try your library inside my projects with complex layouts. I hope having no problem

**Comment by dmitry-zaitsev** [comment]
I was using Anvil before myself, that's exactly why I made this library :)

If you will have a particular performance issue, just let me know.
